const todasLasCanciones = [

{
    titulo:"GAUCHO",

    autor:"LA JOAQUI",

    audio:"audios/GAUCHO.mp3",

    letra:`LA NENA BUENA DE LOS NENES MALOS.

ME GUSTA CON ESA CARA DE MALO,
CON LOS OJOS ROJOS, LA PISTOLA DE COSTADO.
MARGINADO, YO LO AMO. MARGINADO…

POR VOS, MATO Y SACO DE CHETO A LOS GATOS.
POR VOS, MATO Y SACO DE CHETO A LOS GATOS.
MARGINADO, TE ESTÁN BUSCANDO. MARGINADO…

TE VEO LOCO, RE LOCO, MIRÁNDOME,
OJEÁNDOME, COMO DESEÁNDOME
Y YO TE TOCO DE A POCO, ¿Y QUÉ?
SEDUCIÉNDOTE...

LE PIDO AL GAUCHO QUE NUNCA CAIGAS EN CANA.
SI LLEGA LA PATRULLA, BAJAMOS LA PERSIANA.
ALTO, ALTO, ESTO ES UN ASALTO.
EY, CUIDAME, GAUCHO.

CUIDAME, CUIDAME, QUE YO NO SÉ…

MARGINADO, TE ESTÁN BUSCANDO. MARGINADO…
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"SEÑOR KIOSKERO",

    autor:"INTOXICADOS",

    audio:"audios/SEÑOR KIOSKERO.mp3",

    letra:`HOLA, SEÑOR KIOSKERO.
VENGO EN BUSCA DE SU DINERO.
PONGA LAS MANOS ARRIBA
Y PRESTEME MUCHA ATENCIÓN.

MI FAMILIA NO TIENE TRABAJO
Y YO TRABAJAR NO QUIERO,
POR ESO, PONGA EL DINERO
EN ESTA BOLSA, POR FAVOR…

SEÑOR KIOSQUERO... KIOSKERO,
SEÑOR KIOSQUERO... KIOSKERO,

YO NO QUISE HACERLE DAÑO
SOLO QUE ANTES DE IRME, PRIMERO
QUIERO LLEVARME ESE VIDEO
QUE TODO ESTE ASALTO GRABÓ
Y SI ALGÚN DÍ¬A PUEDO, ESPERO
Y EN LA VIDA TENGO MUCHA SUERTE
SI CONSIGO ESTE DINERO
VOY A VENIRSELO A TRAER.

NO ME GUSTA LO QUE LE ESTOY HACIENDO,
PERO SEÑOR KIOSKERO, YO TRABAJAR NO QUIERO.
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"MÓNACO",

    autor:"DESAKTA2",

    audio:"audios/MÓNACO.mp3",

    letra:`DIME…
ESTO ES LO QUE TÚ QUERÍA'
YO SOY FINO, ESTO ES TRAP DE GALERÍA.
TÚ ERES UN CHARRO, ROCKY THE KID, UNA PORQUERÍA.
(YO CAMPEÓN) ROCKY MARCIANO, ROCKY BALBOA, ROCKY MALVÍA.
TENGO LA RUTA, TENGO LA VÍA, SÍ, YO TENGO LA VÍA.
LOS GASTO' DE NOCHE, FACTURO TO' EL DÍA.
TANTA PLATA, QUE, QUE ME GUSTA QUE
ME CHAPEEN, POR ESO LE METO A TODA' ESTA' ARPÍA’.

NO SABEN LO QUE ES ESTAR EN ALTAMARCON DOSCIENTOS CUERO',
QUE LA AZAFATA TE MAME EL BICHO EN EL CIELO,
LO QUE ES TIRAR QUINIENTO' MIL EN EL PUTERO.
POR ESO, TU OPINIÓN ME IMPORTA CERO.
POR ESO, TÚ ESTÁS 101 EN EL TOP 100 Y YO ESTOY PRIMERO.
YA NO SOY RAPERO, AHORA SOY CUARTETERO.
MÁS QUE TÚ, ESTÁ COBRANDO MI BARBERO,
CHINGANDO Y VIAJANDO EN EL MUNDO ENTERO.

BEBIENDO MUCHA CHAMPAÑA, NUNCA ESTAMO' SECO'.
PRIMERO LLEGÓ VERSTAPPEN, DESPUÉS LLEGÓ CHECO,
SI PABLO ME VIERA, DIRÍA QUE SOY UN BERRACO.
USTEDE' HABLANDO MIERDA Y YO Y LO' MÍO' POR MÓNACO.

BEBIENDO MUCHA CHAMPAÑA, NUNCA ESTAMO' SECO'.
ESTÁN HABLANDO SOLO', ESTÁN HABLANDO CON EL ECO.
EL SIGNO DEL DINERO, ESE ES MI NUEVO ZODIACO.
PRENDO UN PURO, LA FAMILIA ESTÁ EN MÓNACO.

LO' CARRO' DE F1 SON MA' RÁPIDO' EN PERSONA.
SOFÍA VERGARA ES LINDA, PERO MA' LINDA EN PERSONA.
LO QUE TÚ HAGA', A MÍ NO ME IMPRESIONA,
ES COMO METER UN GOL DESPUÉS DE MESSI Y MARADONA.
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"PINTA",

    autor:"L-GANTE, BIZARRAP & PABLO LESCANO",

    audio:"audios/PINTA.mp3",

    letra:`NOSOTROS TAMBIÉN TENEMOS CÓDIGO' (COMPA).
BIZARRAP, GRABÁ ESTE VILLARRAP (WUPI, WUPI).

YO TENGO ESTA PINTA PORQUE PINTÓ.
VISERA', GAFA', ZARPADO EN CONJUNTO,
NO ME CABE QUE ME FALTEN EL RESPETO,
NO ME APUREN QUE YO SIEMPRE ANDO BIEN SUELTO
Y YA ME CONOCEN POR VARIOS BARRIO'.
CAEMO' DE CHETO Y NO COMPRO CON LOS OTARIO',
TO' LOS PIBE' DE LA CALLE ESTÁN LUCHANDO PA' COMER,
YO TENGO PA' PREGUNTAR Y TAMBIÉN PA' RESPONDER.

Y CONMIGO NO TE CREA' QUE ME VA A CALLAR CUALQUIERA.
MI PUEBLO ME CRÍO PA' DEFENDERME CON QUIEN SEA,
MUCHO' QUE NO BANCAN NADA SI TE LOS CRUZA' SIN CHAPA,
YO ANDO FUMANDO DE NOCHE Y LA ENVIDIA MATA.

ME QUIERE PARAR LA GORRA,
QUE NO ESPERE, QUE CORRA.
YO ANDO TRANQUI, SOLO, TOMANDO UNA BIRRA Y FUMANDO UNA SECA,
SIEMPRE EN LA ESQUINA, ATENTO PARA QUE LO SEPA'.
SI ME VA A PARAR LA GORRA,
QUE NO ESPERE, QUE CORRA.
YO ANDO TRANQUI, SOLO, TOMANDO UNA BIRRA Y FUMANDO UNA SECA
SIEMPRE EN LA ESQUINA, ATENTO PARA QUE LO SEPA' (¿QUÉ? ¿QUÉ?)

PERRO, ACÁ DONDE VIVIMO', LOS PIBITO' SOMOS VAGO',
LA HUMILDA' ES EN LA CALLE Y LA CALLE SABE CÓMO HAGO
PA' QUE ARRANQUEN Y DEJARLO' BIEN CALLADO'.
SIEMPRE CON LO' OJOS TUMBADO' Y UN VINITO EN UNA BOTELLA CORTADA,
QUE SI PINTA DE NOCHE, ME IDENTIFICAN,
VAMOS TIRANDO HUMO POR EL AIRE CON LA CLICKA.
ADENTRO DEL BAILE YA SABEN QUÉ SIGNIFICA
SI TIRAMO' LOS PROHIBIDO' CON EL COMBO QUE LA APLICA.

TE CRUZA' DE CALLE SI NOS VES DE NOCHE,
NOS GUSTA ANDAR POR LA OSCURIDAD,
PA'L MUNDO SIEMPRE FUIMO' MARGINADO',
SIN IMPORTAR NUESTRA IDENTIDAD.
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"STREET POEM",

    autor:"ANUEL AA",

    audio:"audios/STREET POEM.mp3",

    letra:`PREGUNTA SI LA AMO.
DICE, SÉ SINCERO,
NO LO COJAS PERSONAL,
SOLO PIENSO EN DINERO.
PERO TE LO PROMETO,
VOY A SER HISTORIA
Y AUNQUE ME ODIEN,
VAN A TENERME EN SU MEMORIA.

NO ME MIENTAS, EMMA,
Y MÍRAME A LOS OJOS.
¿ESTAS ARREBATAO?
PORQUE LOS TIENES ROJOS.

IT I DON'T FUCK.
TU SABES NO TE MIENTO.
PERO TE ME ENCOJONAS SI TE DIGO LO QUE SIENTO.
MIRA LA LUNA QUE COMO TUS OJOS TA' BRILLANDO,
NO ME VUELVAS A DECIR QUE EN TI NO ME PASO PENSANDO,
QUE SI ME OLVIDO DE TI SIEMPRE QUE GRABO
PERO TENGO QUE SER MILLONARIO PA' SEGUIR HACIENDO CHAVOS.

Y DARTE LO QUE NECESITES Y LO QUE TE MERECES.
SOÑE CON UNA COMO TU CUANDO CUMPLI LOS 13,
EN LA ESCUELA ERA LA MAESTRA Y YO ERA EL JEFE
PERO EN LAS PRUEBAS DEL AMOR SIEMPRE SACABA F

NUESTRA RELACIÓN ES COMPLICADA
Y SIN QUERER LE ESTOY HACIENDO DAÑO A MI AMADA
COMO SI BREGARA CON SUSTANCIAS CONTROLADAS
ESTOY FUGAO’, EL AMOR ME BUSCA Y ELLA PREOCUPADA.

AUNQUE LA VERDAD DUELA PERO LAS MENTIRAS SANAN,
ÍNTIMAMENTE TENGO PROBLEMAS
QUE OFENDEN A LOS PANAS Y A LAS NENAS,
POR ESO CON CRISTINA MATO LAS PENAS.
SI EL MAL NOS SEPARA SOY TU PIRATA Y TU MI SIRENA.

NO SÉ SI ME ENTIENDAS,
EL AMOR NO FUE UNA DROGA PA' QUE NO SE VENDA.
Y COMO TENER LA TIENDA SI NO HAY PLATA PA’ LA RENTA,
TE AMO PERO IF YOU AIN'T WIT PA' LA VENTA
NO SÉ SI TU COMPRENDAS.

HASTA QUE SE ACABE EL MUNDO…
TU Y YO CRISTINIANDO,
THUG LIFE EL MOTE YO LO GRITANDO,
REAL NEGGAS BIEN LONELY TOONS.
SOY REAL, UN BANDIDO
NO TU PRINCIPE AZUL
WHAT IF I DIE
IF I DIE
TONIGHT I BE ROLLING AIR PLANES
FUCK AROUND THIS FLIGHT I REMEMBER WHEN SHE SAID
FUCKING MISS YOUR TIME
GOT AMBITION IN MY VEINS
MONEY ON MY MIND

BARRABARAOU
COMO SUFRÍ, FUI TRAICIONAO
NO ME COMPARO PA' QUE DIGAS QUE ESTOY EMPICHONAO BEBÉ,
NO SE SI HAY UN CIELO PA' ALGUIEN QUE LE GUSTA ANDAR ARMAO
PERO SI MUERO NO ME OLVIDES
EL DE LOS OJOS COLORAOS WAO EIH
ESTOY FUGAO DESDE LOS 16
NO SOY UN DEMONIO LOS OJOS SON ROJOS POR EL HAZE,
COMO WALEI, YA NI ME ENAMORO.
NO LE CANTO A LOS COROS.
LLORE POR UNA PUTA NIÑA, CRÉEME NO LLORO.
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"AHORA ESTOY SOLO",

    autor:"LA T Y LA M",

    audio:"audios/AHORA ESTOY SOLO.mp3",

    letra:`¿QUÉ VOY A HACER?
SÍ, YA SÉ QUE NO ME QUIERES.
¿QUÉ PUEDO HACER?
SI YA MIS SUEÑOS SE FUERON.

SIENTO QUE NO PUEDE SER
Y QUE TIENES QUE VOLVER.
NO, NO PUEDE SER,
NO PUEDO AMARTE
Y CUANDO MENOS LO PENSABA
TODO FUE A TERMINAR ENTRE LOS DOS.

Y AHORA ESTOY SOLO (SOLO)
SIN TU CARIÑO NO TENGO NADA.

RECORDARÁS (¿QUÉ?)
TANTAS PROMESAS QUE HICIMOS
Y VIVIRÁS…
PENSANDO SOLO EN MI CARIÑO.
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"NO FORCEN",

    autor:"ANUEL AA, OZUNA & YAMPI",

    audio:"audios/NO FORCEN.mp3",

    letra:`TO' ESTOS CABRONES ME QUIEREN MATAR
PERO YO TENGO TRES PALESTINOS,
NOSOTROS MOVEMOS LOS KILOS Y YA TENGO
UNA BALA PA' CADA ENEMIGO.

CONMIGO NO FORCE, SI YA TÚ SABES,
QUE ME PASÓ QUEMANDO Y GASTANDO CON PILA DE MAMI.
CONMIGO NO FORCE, ME COMPRÉ MI FULETE EN 14,
ME MONTÉ UN BOTE PA' LAS ISLITAS Y COMPRÉ LOS TRABAJOS A 12.

ELLA SE TRAGA ESE BICHO EN MI CUEVA.
YO SOY EL DIABLO, EL MÁS PURO DE LA NUEVA.
ENTRO PA' LA DISCO Y PIDO 100 BOTELLAS,
ESTOY CON PAPOTITO, UN DEMONIO DE CANTERA.

LA SANGRE SOBRE EL AGUA PESA,
TENEMOS ENCIMA OCHO PIEZAS.
Y TO' EL QUE ME VENGA DE CHOTA Y VIRA'O.
EL AK CON EL PICO LO BESA.

CABRÓN, YO NUNCA HE TENIDO UNA BERETTA.
YO TENGO UNA GLOCK FULETA CON DOS TETAS.
LOS MÍOS SON TAN NATURAL, TARJETA NEGRA,
NO CORRO CON FECAS.

TENGO UNA VENEZOLANA
QUE LE GUSTA LA MARIHUANA.
TENGO UNA COLOMBIANA
QUE LO QUE ME PIDE
ES QUE YO LE DÉ FLAMA.

Y SALIMO' READY, LOS R Y LAS GLOCK
ACICÁLAME, MAMI, A TODITAS MATÓ.
SALIMO' READY, ROMPIMOS EL CLUB.
ACICÁLAME, MAMI, A TODITAS ELLA LAS MATÓ.

A VECES QUISIERA SABER
POR QUÉ ES QUE LA COGEN CONMIGO.
SERÁ PORQUE ESTAMOS BRILLANDO
Y MATANDO, YO TENGO LO MÍO.

EL TONKA COMPRÓ 30 RIFLES Y VAMOS A CAZAR
HASTA QUE LOS MATEMO' A TODO'.
LLEGAMO' EN LA RAPTOR Y EN EL PORSHE
CON LOS DE PLAYITA Y BAYAMÓN.

LOS DRAKOS TO' TIENEN TAMBORES
Y TO' LAS GLOCK TIENE PEINE DE EXTENSIÓN.
LOS COMPRE EN ROBERTO CLEMENTE
PERO LOS VENDÍ EN 33 EN EL BRONX.

EL DEA ME MAMA EL BICHO
DESPUÉS QUE JOCKEY SE BAJA DEL AVIÓN,
CORONAMOS DESPUÉS QUE LOS PÁJAROS BLANCO'
ATERRICEN EN NUEVA YORK.

ORO AMARILLO EN MI CUELLO, MIL DOS EN MIS GAFAS,
CABRÓN YO SOY HÉCTOR LAVOE.
YO ME MONTO CON JAIMITO Y TE VAN A VER MUERTO
EN NOTICENTRO CON TU PATRÓN.

OZUNA.
OZUNA.

EL AÑO 7000.
YO SOY INTOCABLE COMO EL TONKA.
ME VOY A CAGAR EN LA MADRE DEL DIABLO.
REAL HASTA LA MUERTE, ¿OISTE CABRÓN?
ANDO CON YAMPI.
EL AÑO 7000.
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"CREO",

    autor:"CALLEJEROS",

    audio:"audios/CREO.mp3",

    letra:`CREO QUE CON UNA CANCIÓN LA TRISTEZA ES MÁS HERMOSA
CREO QUE CON UNA PALABRA PUEDO DECIR MIL COSAS
PERO NO CREO EN EL CIRCO DE LA INFORMACIÓN
TODO DECANTA EN TU AMOR
Y EN MI DOLOR.

CREO QUE ES MEJOR MORIR DE PIE QUE VIVIR DE RODILLAS
CREO QUE HOY EL VIENTO ME ALCANZÓ EL OLOR DE TU MEJILLA
CREO EN MI GUITARRA, CREO EN EL SOL
SI ME CURA LAS HERIDAS
CREO EN TU VOZ.

CREO EN LA VIDA, EN LA NOCHE, EN TU ALMA
Y NO CREO EN TODO LO DEMÁS
CREO EN TU ESTRELLA, EN AQUELLA QUE BUSCO EN MI SUEÑO MEJOR
PARA PODER LUCHAR.

CREO EN ESAS TARDES QUE VIVÍ JUGANDO A LA PELOTA
CREO QUE EDUCAR ES COMBATIR Y EL SILENCIO NO ES MI IDIOMA
CREO EN TU SONRISA, CREO EN MÍ SI TE VEO HOY
Y ME PEDÍS QUE NO ME RINDA
SIGO POR VOS.

CREO EN LA LLUVIA CUANDO CAMBIA EL OLOR DE MI TIERRA
CREO EN EL MAR CUANDO AMANECE ABRAZÁNDOSE A LAS PIEDRAS
CREO EN LOS JAZMINES QUE UN DIOS ME BAJÓ ESA VEZ
PARA PODER CONOCERTE
COMO MUJER.

CREO EN LA VIDA, EN LA NOCHE, EN TU ALMA
Y NO CREO EN TODO LO DEMÁS
CREO EN TU ESTRELLA, EN AQUELLA QUE BUSCO EN MI SUEÑO MEJOR
PARA PODER LUCHAR.

CREO EN LA VIDA, EN LA NOCHE, EN TU ALMA
Y NO CREO EN TODO LO DEMÁS
CREO EN TU ESTRELLA, EN AQUELLA QUE BUSCO EN MI SUEÑO MEJOR
PARA PODER LUCHAR.
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"SOY FAVELA",

    autor:"LA T Y LA M",

    audio:"audios/SOY FAVELA.mp3",

    letra:`HE CAMINADO TANTAS CALLES
PERO NO HE ENCONTRADO A NADIE
QUE TENGA TODA SU BELLEZA
SOY DE UN BARRIO HUMILDE
PERO AÚN MI CORAZÓN SE ENAMORÓ
DE ESTA CENICIENTA.

ELLA DE ZONA SUR
BONITA, OJOS AZUL
PERO SU PADRE ES EL PROBLEMA
NO IMPORTA MI COLOR
NI MI CONDICIÓN
ELLA ES LA DUEÑA DE MI CORAZÓN.

HOY YO LA VOY A VER
Y VOY A HABLAR DE LA VERDAD CON ELLA
HOY YO LA VOY A VER
Y VOY A HABLAR DE LA VERDAD CON ELLA

HEY!
DILE A TU PADRE QUE YO NO QUIERO DINERO
QUE YO TENGO UNA RIQUEZA Y QUE ERES TÚ
SI QUIERES CASAR, ME CASO
VAMO' A INTENTARNOS
AMARNOS MUJER.
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"7 VIDAS",

    autor:"MARÍA BECERRA",

    audio:"audios/7 VIDAS.mp3",

    letra:`ANOCHE TERMINÉ ROTA, TÚ DESGARRASTE MI CORAZÓN.
VI QUE ME CAMBIASTE POR OTRA Y YO ESPERÁNDOTE EN UN PABELLÓN
Y MIRA CÓMO ES LA VIDA Y YA NO SÉ LO QUÉ ES PEOR,
ESTAR PAGANDO ESTA CONDENA O EL BESO DE TU TRAICIÓN

VOY A SALIR UN DÍA DE AQUÍ
PA' COBRARTE LO QUE HICISTE CONMIGO. (DICE)

PARA QUE TE ACUERDES DE MÍ, PARA QUE TE ACUERDES DE MÍ,
MALDITO GATO,  EN TUS SIETE VIDAS TE HARÉ INFELIZ.
PARA QUE TE ACUERDES DE MÍ, PARA QUE TE ACUERDES DE MÍ,
QUE EL DÍA QUE MUERAS, YO TE REVIVO Y TE HAGO SUFRIR. (EY)

EL DÍA QUE TE ARREPIENTAS TE ESPERO CON LA 40.
UNA PA' CUPIDO Y OTRA PARA VOS.
SIN MIRAR LA LUZ DEL DÍA, CUALQUIER CORAZÓN SE ENFRÍA
Y HOY SOLO PALPITA ODIO Y RENCOR.

VOY A SALIR UN DÍA DE AQUÍ
PA' COBRARTE LO QUE HICISTE CONMIGO. (DICE)
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"LA GERENCIA",

    autor:"TITO EL BAMBINO, FRONTI, WISIN, HANZEL LA H y ARCÁNGEL",

    audio:"audios/LA GERENCIA.mp3",

    letra:`AQUÍ NO HAY QUE DEMOSTRAR NADA
ESTO SE TRATA DE RESPETO
LA GERENCIA

SALIMO' DE LA CALLE Y DEL GHETTO, Y EL RESPETO LO IMPLANTAMO'
EN LA DISCO ESTÁN VOLANDO LAS PACA'
Y AL QUE NO LE GUSTE, LO SACAMO' (TÚ SABE')
NO PUEDEN, NO PUEDEN, CON NOSOTROS NO
PORQUE EN LA DISCO ESTÁN VOLANDO LAS PACA'
Y AL QUE NO LE GUSTE, LO SACAMO'.

DICEN QUE, DICEN QUE NO IBAMO' A LLEGAR, AH (TITO "EL BAMBINO")
SE QUEDAN FRÍO' CUANDO EL PATRÓN EXHALA (PAH)
TENEMO' PLATA, PALABRA' Y TO'AS LAS BALA' (PAH)
LIBRA POR LIBRA Y NINGUNO NOS IGUALA
SALIMO' A LA CALLE Y LA PRESIÓN SE SIENTE (AH)
YO SOY EL PATRÓN, COMPARARSE, NO PUEDEN
MÚSICA DEL PARQUE QUE AHORA SUENA MUNDIALMENTE (AJÁ)
¿TÚ ERE' LOCO O NO ENTIENDE'?
YO NO TIRO REDE', TE TRABAJO DE FRENTE (DURO)
AQUÍ NO PELEAMO', TE BORRAMO' LOS DIENTE'
NO METES FEKA NI TÚ, NI TU GENTE
SI TIRAN PA' ACÁ, LAS BALA' 'TÁN CALIENTE'

LAS BALA' 'TÁN CALIENTE'
(LAS BALA' 'TÁN CALIENTE')
LAS BALA' 'TÁN CALIENTE'
(LA SOCIEDAD DEL DINERO, ¿OÍSTE?)

'TAMOS SUBIENDO DE LEVEL, A MÍ EL QUE ME BENDIJO, NO LO PUEDO VER
TÚ ESCUCHA' UN TIRO, BRO, Y TE VA' A CORRER, BRR, BRR, BRR, BRR
PA' ACÁ NO TE PEGUE' A JODER
QUE LOS TIEMPO' LE CAMBIARON A LOS QUE NO TENÍAN PODER
SEGUIMO' POWERFUL, ANDO CON SETENTA Y NO SOY HÉCTOR
TO'AS LAS GLOCK CON CHIPETE PA' MATAR INSECTO'
NO, YO NO, YO NO RONCO 'E CALLE, LO DEMUESTRO
SÍ, YO SÍ, YO SÍ QUE ME MONTO Y LOS SECUESTRO
YO NO ME CAIGO DESDE QUE ME CONECTÉ
ANTES YO QUERÍA LAS PRENDA', AHORA YO BRILLO SIN LOS BAGUETTE
DEL CIELO ME CAEN LAS PACA' Y YO DIZQUE BUSCANDO LA FE
YO ESTOY AGARRA'O DE CRISTO, ¿QUIÉN CARAJO' VA A HACER QUÉ?
POWERFUL, ANDO CON SETENTA Y NO SOY HÉCTOR
TO'AS LAS GLOCK CON CHIPETE PA' MATAR INSECTO'
NO, YO NO, YO NO RONCO 'E CALLE, LO DEMUESTRO
SÍ, YO SÍ, YO SÍ QUE ME MONTO Y LOS SECUESTRO

JUMBO, ¿ME COPIA'?
SON DÉCADA' REPARTIENDO EL BACALAO.

ME MONTÉ EN EL NOVA (YEAH), VOY BAJANDO PA' CAROLA (YEAH)
TITO, QUE SE AQUIETEN, O LOS VA A ARROPAR LA OLA (EH)
DE CAROLINA A SAN JUAN, DE TRUJILLO A CAYEY
SI ME HACEN UN FAKE, VAN A SABER QUIÉNES SON LOS HEAVYWEIGHT (DOBLE)
PAPI, NO TRATE', QUE HAY MÁS PLATA, MÁS PESO
UN GALLO CASTA'O, GUERRERO, SIN RETROCESO (PAH)
PAPÁ W, SI ME ACTIVO, TE ENDEREZO
MEJOR QUÉDATE QUIETO O TE DEJAN IMPRESO (EY)
AQUÍ TO' EL MUNDO ESTÁ PROBA'O (AJÁ)
NOSOTROS SIEMPRE ANDAMOS EN JET PRIVADO MONTAO'
POR LAS COSTAS DE MÓNACO CON EL PORSCHE ESMANDA'O
SIEMPRE SE HA QUEDA'O EL QUE CONMIGO SE HA RIFA'O
Y NO ME HABLEN DE GUERRILLA, NI DE QUE ANDAN CON LA PANDILLA
YO HAGO TRE' MOVIMIENTO' Y LE VIRAMO' LA TORTILLA
LO QUE TÚ GANA' EN UN AÑO, VALE MI GARGANTILLA
AUNQUE APARENTE' QUE ERES DURO, SIGUES SIENDO UNA BARQUILLA.

SALIMO' DE LA CALLE Y DEL GHETTO, Y EL RESPETO LO IMPLANTAMO'
EN LA DISCO ESTÁN VOLANDO LAS PACA'
Y AL QUE NO LE GUSTE, LO SACAMO' (TÚ SABE')
NO PUEDEN, NO PUEDEN, CON NOSOTROS NO
PORQUE EN LA DISCO ESTÁN VOLANDO LAS PACA'
Y AL QUE NO LE GUSTE, LO SACAMO'

CUANDO YO LLEGO SE GLITCHEAN Y LAS BABIE' LES PICHEAN
TO'A ESTA COMBI ES LV, HASTA LAS GAFA' ME MATCHEAN
SIGO CHAMPION, JOSÉ JUAN BAREA
SI NO ERE' DE ESTA MATRÍCULA, TE LA VAMO' A APLICAR EN DÓNDE SEA
LA DISCO ESTÁ PRENDÍA' Y EL VIP REPLETO
LAS BABY TO'AS SON MÍA' Y LAS PRENDA' DE AMULETO
SI NOS FALTAS, TE MATAMO', ESTO ES RESPETO POR RESPETO
TANTA PLATA QUE HICE CHAVO' PA' LOS NIETO' DE MIS NIETO'
ME PUEDO RETIRAR, VIVO TRANQUILO
EL MEJOR LIBRA POR LIBRA UNA PUÑETA, EL MEJOR KILO POR KILO
ESTE FLOW ESTÁ BELLACO, NO SE VENDE NI SE ALQUILA
ESTA GENTE ANDAN EN RETRO, PERO ESTÁN HACIENDO FILA
'TOY BURLETE, LERO-LERO, SIN SALIR YA ESTOY PRIMERO
ESTO ES DE PARQUE HASTA CATAÑO, LA SOCIEDAD DEL DINERO
VO'A VIAJAR EL MUNDO ENTERO, Y SI ALGÚN DÍA YO MUERO
BYE, SE MURIÓ UN GUERRERO, COMO BRAYY EN BARRIO OBRERO, YEAH.

EY
VAMO' A DARTE UNA LEVE EXPLICACIÓN DEL MODUS OPERANDUM QUE TENEMO' NOSOTRO'
AUH

YO ME MUEVO COMO UN PATRÓN (YEAH)
NO ME CABE OTRA PACA EN LOS BOLSILLO' DEL MAHÓN (NO, NO, NO)
TAMPOCO MUNICIÓN EN EL CLAVO DEL RUBICON (WUH)
YO TENGO TICKET, NO ME CABE MÁS CRUCE' EN EL BULTO CHROME
OH, MY GOD, A MÍ NO ME IMPORTA LO QUE AQUEL TUVO (NO)
CADA AÑO QUE PASA, MÁS DE PRECIO SUBO (YES), EY
YO TENGO UN AMANSABRAVO' PA' LOS RUDO' (PRRA)
CON LA FMJ QUE TRASPASA LOS ESCUDO' (AUH)
YO SOY ARCA, AUNQUE NO HAGA FRÍO, DE PRADA ES EL BEANIE (BEANIE)
SE NOTA EL PEINE LARGO QUE LE PUSE A LA MINI (MINI)
PA' PRENDERTE EN FUEGO COMO EL SOL DE PHOENIX (YEAH)
FREE LA H, FREE DOBLETA, FREE CHIMI (WUH), YEIH
LA LEYENDA ENTRANDO, DAMAS Y SEÑORE' (DAMAS Y SEÑORE')
NUNCA HE TOCA'O INSTRUMENTO' Y LOS PALO' TIENEN TAMBORE' (RU-TU-TU-TUN)
YO NO CORRO POR CHISME', NI POR RUMORE' (NO)
EN ESTE NIVEL QUE ESTAMO', NO SUBEN LOS ASCENSORE' (YEAH), SHH
NO SUBEN NI LOS PILOTO' (-LOTO')
Y NO BUSQUEN QUE SU CASA CON BOQUETES SE LAS DECORE (PRR, WUH)
CUANDO HABLEN DE MÍ, QUE LO DIGAN BIEN
YO SOY EL MEJOR, YO NO SOY UNO DE LOS MEJORE' (ARCA), PRRA

OKEY
W, WISIN
HANZEL LA H
ESTA ES LA GENTE DEL PATRÓN
FRONTI (LA SOCIEDAD DEL DINERO, ¿OÍSTE?)
Y, DE PATRÓN A PATRÓN
ESTO VIENE SIENDO UNA CONVERSACIÓN DE PATRONES, PRRA
LA SOCIEDAD DEL DINERO
HANZEL LA H "EL DE LOS OJOS BLANCOS"
JUMBO "EL QUE PRODUCE SOLO"
MERA, DIME, MUEKA
HYDE "EL QUÍMICO", DIRECTAMENTE DESDE LA BASE, AUH
PRRA
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

},

{
    titulo:"UNA NOCHE EN MEDELLÍN",

    autor:"CRIS MJ",

    audio:"audios/UNA NOCHE EN MEDELLÍN.mp3",

    letra:`NENA, DIEZ CENTAVOS SI TÚ 'TÁ PA' MÍ,
COMO YO 'TOY PUESTO PA' TI,
TE LLEVO UNA NOCHE A MEDELLÍN
Y TE PAGO EL GYM.
NENA, DIEZ CENTAVOS SI TÚ 'TÁ PA' MÍ,
COMO YO 'TOY PUESTO PA' TI,
TE LLEVO UNA NOCHE A MEDELLÍN
Y TE PAGO EL GYM.

TE VOY A HACERTE COMPLETA,
'TÁ BUSCANDO QUE YO LE META,
YA LLEGAMO' A LA META,
AHORA NADIE APRIETA
Y AHÍ ME PUSE LAS BALENCIAGA.
MAMI, NO TE HAGA', VENTE PA'CÁ, TÚ ERE' BRAVA.
ME GUSTA PORQUE ERE' MALVADA,
NO ESTÁ OPERADA Y ASÍ MATA LAS MIRADA'
Y ME AYUDA A CONTAR BILLETE'.
SACA SU JUGUETE, TO' YA SABEN QUE LE METE.
TÚ SABES', NO ANDO AL GARETE,
ENCIMA MÍO TE QUITO EL BRAZALETE.

SI TÚ QUIERES' YO TE PAGO EL GYM
TE LLEVO AL MANDARÍN Y TE HAGO BLIN-BLIN,
MI IPHONE SUENA "RING, RING",
ME ESTÁ LLAMANDO EL DINERO FÁCIL, GOTEANDO MI GOTEO.
ESA GATA LO QUE BUSCA E' GUAYETEO, FUMETEO,
QUE YO ME LA ROBE Y FORMEMO' EL PARTYSEO.
A MÍ ME GUSTA EL REBULEO, A TI TE GUSTA EL BELLAQUEO
COMO YO A TI TE LEO, ASÍ QUE TOMA GUARACHEO
QUE SI YO ME ENRE'O Y AHORA MISMO TE VOLTEO, MA'
TÚ ERE' LA ÚNICA QUE SABE MI DESEO',
A TI YO NO TE BROMEO
BABY, HAGÁMOSLO SIN MIEDO (BRR).

EY, EY.
CRIS MJ, EL MÁ' QUE SUENA
PA' QUE SEPA'.
DÍMELO, FRAN C IN THE BEAT.
MATANDO A LO' MÁ' LECHÓN
PRRA.
PERREO PA' QUE LO BAILEN
FRAN C IN THE BEAT.
YA SABEN QUÉ LO QUE
STARS MUSIC.
`,

    imagen:"",

    video:"",

    preguntas:[],

    respuestas:[],

    analizada:false

}

];
